ci: Add unit test code coverage check (#305)
Edited the unit test workflow:
- The unit test coverage calculation excludes the `sources` and `tools`
packages (but we still run them without coverage).
- Generate a code coverage analysis file `coverage.out` and fail the
unit test if the total coverage is below 40% (target at 90%)

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -26,7 +26,7 @@ permissions: read-all
 
 jobs:
   integration:
-   # run job on proper workflow event triggers (skip job for pull_request event from forks and only run pull_request_target for "tests: run" label)
+    # run job on proper workflow event triggers (skip job for pull_request event from forks and only run pull_request_target for "tests: run" label)
     if: "${{ (github.event.action != 'labeled' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name) || github.event.label.name == 'tests: run' }}"
     name: unit tests
     runs-on: ${{ matrix.os }}
@@ -61,7 +61,7 @@ jobs:
         uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
         with:
           go-version: "1.22"
-      
+
       - name: Checkout code
         uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
         with:
@@ -76,4 +76,20 @@ jobs:
         run: go build -v ./...
 
       - name: Run tests
-        run: go test -race -tags="!integration" -v ./...
+        run: |
+          source_dir="./internal/sources/*"
+          tool_dir="./internal/tools/*"
+          auth_dir="./internal/auth/*"
+          included_packages=$(go list ./... | grep -v -e "$source_dir" -e "$tool_dir" -e "$auth_dir")
+          go test -race -cover -coverprofile=coverage.out -v $included_packages
+          go test -race -v ./internal/sources/... ./internal/tools/... ./internal/auth/...
+
+      - name: Check coverage
+        run: |
+          total_coverage=$(go tool cover -func=coverage.out | grep "total:" | awk '{print $3}')
+          echo "Total coverage: $total_coverage"
+          coverage_numeric=$(echo "$total_coverage" | sed 's/%//')
+          if (( $(echo "$coverage_numeric < 40" | bc -l) )); then
+              echo "Coverage failure: total coverage($total_coverage) is below 40%."
+              exit 1
+          fi
